.\" Manpage for AcousticSolver
.\" Contact c.cantwell@imperial.ac.uk to correct errors or typos
.TH man 1 "07 Aug 2019" "5.0" "AcousticSolver man page"
.SH NAME
AcousticSolver \- solves acoustic wave propagation problems
.SH SYNOPSIS
AcousticSolver [[session.xml] ... ]
.SH DESCRIPTION
AcousticSolver solves acoustic wave propagation partial differential
equations using the spectral/hp element method. It is built on the Nektar++
high-order spectral/hp element framework.
.SH OPTIONS
session.xml \- One or more input session files describing computational domain
and parameters.
.SH BUGS
No known bugs.
.SH AUTHOR
Chris Cantwell (c.cantwell@imperial.ac.uk)
