# CMake generated Testfile for 
# Source directory: /tmp/ybao/nektar++/solvers/IncNavierStokesSolver
# Build directory: /tmp/ybao/nektar++/builds/solvers/IncNavierStokesSolver
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(IncNavierStokesSolver_Kovasznay_Flow_3modes "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Kovasznay_Flow_3modes.tst")
ADD_TEST(IncNavierStokesSolver_2DFlow_lineforcing_bcfromfile "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/2DFlow_lineforcing_bcfromfile.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow2D_bcsfromfiles "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow2D_bcsfromfiles.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_LinNS_m8 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_LinNS_m8.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m3 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m3.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m3_SKS "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m3_SKS.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m8 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m8.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m8_BodyForce "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m8_BodyForce.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m8_singular "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m8_singular.tst")
ADD_TEST(IncNavierStokesSolver_Channel_Flow_3modes_rad "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Channel_Flow_3modes_rad.tst")
ADD_TEST(IncNavierStokesSolver_Hex_channel_m3 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Hex_channel_m3.tst")
ADD_TEST(IncNavierStokesSolver_Pyr_channel_m3 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Pyr_channel_m3.tst")
ADD_TEST(IncNavierStokesSolver_HM "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/HM.tst")
ADD_TEST(IncNavierStokesSolver_HM_Adj "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/HM_Adj.tst")
ADD_TEST(IncNavierStokesSolver_SM "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/SM.tst")
ADD_TEST(IncNavierStokesSolver_SM_Adj "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/SM_Adj.tst")
ADD_TEST(IncNavierStokesSolver_KovaFlow_m3 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/KovaFlow_m3.tst")
ADD_TEST(IncNavierStokesSolver_KovaFlow_m8 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/KovaFlow_m8.tst")
ADD_TEST(IncNavierStokesSolver_KovaFlow_m8_short_HOBC "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/KovaFlow_m8_short_HOBC.tst")
ADD_TEST(IncNavierStokesSolver_Kovas_Quad6_Tri4_mixedbcs "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Kovas_Quad6_Tri4_mixedbcs.tst")
ADD_TEST(IncNavierStokesSolver_SinCos_LinNS_3DHom1D "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/SinCos_LinNS_3DHom1D.tst")
ADD_TEST(IncNavierStokesSolver_TaylorVor_dt1 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/TaylorVor_dt1.tst")
ADD_TEST(IncNavierStokesSolver_Tet_channel_m3 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Tet_channel_m3.tst")
ADD_TEST(IncNavierStokesSolver_Tet_channel_m3_dealiasing "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Tet_channel_m3_dealiasing.tst")
ADD_TEST(IncNavierStokesSolver_Tet_channel_m4_per "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Tet_channel_m4_per.tst")
ADD_TEST(IncNavierStokesSolver_ChannelSpongeNSE "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChannelSpongeNSE.tst")
ADD_TEST(IncNavierStokesSolver_ChannelSpongeLNSE "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChannelSpongeLNSE.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_Standard_BodyForce "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_Standard_BodyForce.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_3DH1D_Parallel_mode1 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_3DH1D_Parallel_mode1.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_3DH1D_Parallel_mode2 "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_3DH1D_Parallel_mode2.tst")
ADD_TEST(IncNavierStokesSolver_ChanFlow_m3_par "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/ChanFlow_m3_par.tst")
ADD_TEST(IncNavierStokesSolver_Tet_channel_m8_par "/tmp/ybao/nektar++/builds/tests/Tester" "/tmp/ybao/nektar++/solvers/IncNavierStokesSolver/Tests/Tet_channel_m8_par.tst")
SUBDIRS(Utilities)
