#!/bin/bash
SOLVER=../ADRSolver-g
test ! -x $SOLVER && echo "Solver $SOLVER not found." && exit

    for h in 1 2 3 4 5 6 7 8 9 10; do
        for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
            sed "s/#NUMMODES#/$P/" < Eigen_$h.xml > tmp.xml
            $SOLVER tmp.xml > output.txt
            mv Eigenvalues.txt Eigenvalues_$h_$P.txt
        done
    done

rm -f output.txt
