FROM %%REGISTRY%%:env-%%OS_VERSION%%-default

LABEL maintainer="Nektar++ Development Team <nektar-users@imperial.ac.uk>"

USER root
COPY docker/nektar-env/${UBUNTU_VERSION}_full_packages.txt packages.txt

RUN export DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get install -y $(cat packages.txt) \
	&& rm -rf /var/lib/apt/lists/*

USER nektar:nektar
