//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: LuoRudy91_my
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translators: 25950, pycml: 25949, optimize: 25790)
//! on Fri Mar  4 00:46:30 2016
//! 
//! <autogenerated>

#ifndef NEKTAR_SOLVERS_ADRSOLVER_EQUATIONSYSTEMS_LUORUDY91_MY_HPP_
#define NEKTAR_SOLVERS_ADRSOLVER_EQUATIONSYSTEMS_LUORUDY91_MY_HPP_

#include <CardiacEPSolver/CellModels/CellModel.h>
namespace Nektar

{
    class LuoRudy91_my : public CellModel
    {

    public:
        /// Creates an instance of this class
        static CellModelSharedPtr create(
                const LibUtilities::SessionReaderSharedPtr& pSession,
                const MultiRegions::ExpListSharedPtr& pField)
        {
            return MemoryManager<LuoRudy91_my>::AllocateSharedPtr(pSession, pField);
        }
        
        /// Name of class
        static std::string className;

        /// Constructor
        LuoRudy91_my(const LibUtilities::SessionReaderSharedPtr& pSession,
                     const MultiRegions::ExpListSharedPtr& pField);

        /// Destructor
        virtual ~LuoRudy91_my() {}

    protected:
        /// Computes the reaction terms $f(u,v)$ and $g(u,v)$.
        virtual void v_Update(
                const Array<OneD, const  Array<OneD, NekDouble> >&inarray,
                      Array<OneD,        Array<OneD, NekDouble> >&outarray,
                const NekDouble time);

        /// Prints a summary of the model parameters.
        virtual void v_GenerateSummary(SummaryList& s);

        /// Set initial conditions for the cell model
        virtual void v_SetInitialConditions();
    };
}

#endif
