FIND_LIBRARY(WIN32_BLAS NAMES libblas PATHS
    ${CMAKE_SOURCE_DIR}/ThirdParty)
FIND_LIBRARY(WIN32_LAPACK NAMES liblapack PATHS
    ${CMAKE_SOURCE_DIR}/ThirdParty)

IF (NOT WIN32_BLAS OR NOT WIN32_LAPACK)
    IF (CMAKE_CL64)
        SET(WIN_ZIP_FILE "win64-blas-lapack.zip")
    ELSE()
        SET(WIN_ZIP_FILE "win32-blas-lapack.zip")
    ENDIF()

    IF (NOT EXISTS ${TPSRC}/${WIN_ZIP_FILE})
        FILE(DOWNLOAD http://ae-nektar.ae.ic.ac.uk/~dmoxey/${WIN_ZIP_FILE} ${TPSRC}/${WIN_ZIP_FILE})
    ENDIF()
    EXECUTE_PROCESS(
        COMMAND ${CMAKE_COMMAND} -E tar jxf ${TPSRC}/${WIN_ZIP_FILE}
        WORKING_DIRECTORY ${TPSRC}
    )

    FIND_LIBRARY(WIN32_BLAS NAMES libblas PATHS
        ${CMAKE_SOURCE_DIR}/ThirdParty)
    FIND_LIBRARY(WIN32_LAPACK NAMES liblapack PATHS
        ${CMAKE_SOURCE_DIR}/ThirdParty)

    MESSAGE(STATUS ${CMAKE_SOURCE_DIR}/ThirdParty)
    MESSAGE(STATUS ${WIN32_BLAS})
    IF (NOT WIN32_BLAS)
        MESSAGE(FATAL_ERROR "Could not find BLAS library after unzipping!")
    ENDIF()

    IF (NOT WIN32_LAPACK)
        MESSAGE(FATAL_ERROR "Could not find LAPACK library after unzipping!")
    ENDIF()
ENDIF ()

GET_FILENAME_COMPONENT(LAPACK_DIR ${WIN32_LAPACK} PATH CACHE)
LINK_DIRECTORIES(${LAPACK_DIR})

MESSAGE(STATUS "Found Win32 BLAS: ${WIN32_BLAS}")
MESSAGE(STATUS "Found Win32 Lapack: ${WIN32_LAPACK}")