
SET(METIS_SEARCH_PATHS 
	${CMAKE_SOURCE_DIR}/ThirdParty/metis-5.0.2/
	${CMAKE_SOURCE_DIR}/ThirdParty/metis-5.0.2/build/
	${CMAKE_SOURCE_DIR}/../ThirdParty/metis-5.0.2/
	${CMAKE_SOURCE_DIR}/../ThirdParty/metis-5.0.2/build
    ${CMAKE_SOURCE_DIR}/ThirdParty/dist/lib 
    ${CMAKE_SOURCE_DIR}/../ThirdParty/dist/lib)

FIND_LIBRARY(METIS_LIB NAMES metis PATHS ${METIS_SEARCH_PATHS})

SET(METIS_FOUND FALSE)
IF (METIS_LIB)
  SET(METIS_FOUND TRUE)
  GET_FILENAME_COMPONENT(METIS_PATH ${METIS_LIB} PATH)
  INCLUDE_DIRECTORIES(${METIS_PATH}/../include)
  MARK_AS_ADVANCED(METIS_PATH)
  MARK_AS_ADVANCED(METIS_LIB)
ENDIF (METIS_LIB)

IF (METIS_FOUND)
  IF (NOT METIS_LIB_FIND_QUIETLY)
     MESSAGE(STATUS "Found Metis")
  ENDIF (NOT METIS_LIB_FIND_QUIETLY)
ELSE(METIS_FOUND)
  IF (METIS_LIB_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find Metis")
  ENDIF (METIS_LIB_FIND_REQUIRED)
ENDIF (METIS_FOUND)
