
FIND_PATH(CHUD_FRAMEWORK_INCLUDE_DIR cblas.h /usr/include /usr/local/include
	/System/Library/Frameworks/vecLib.framework/Versions/A/Headers/ )

MARK_AS_ADVANCED(CHUD_FRAMEWORK_INCLUDE_DIR)

SET( CHUD_FRAMEWORK_LINK_FLAGS "-framework CHUD" )

IF (CHUD_FRAMEWORK_FOUND)
  IF (NOT CHUD_FRAMEWORK_FIND_QUIETLY)
     MESSAGE(STATUS "Found CHUD_FRAMEWORK: ${CHUD_FRAMEWORK_INCLUDE_DIR}")
  ENDIF (NOT CHUD_FRAMEWORK_FIND_QUIETLY)
ELSE(CHUD_FRAMEWORK_FOUND)
  IF (CHUD_FRAMEWORK_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find CHUD_FRAMEWORK")
  ENDIF (CHUD_FRAMEWORK_FIND_REQUIRED)
ENDIF (CHUD_FRAMEWORK_FOUND)
