SET(OCC_DIR "" CACHE FILEPATH "Path to OpenCascade directory")

FIND_LIBRARY(OCC_LIB
	    NAMES PTKernel TKernel TKMath TKBRep TKIGES TKSTEP TKSTEPAttr TKSTEP209 TKSTEPBase TKShapeSchema TKGeomBase TKGeomAlgo TKG3d TKG2d TKXSBase TKPShape TKTopAlgo
		PATHS ${OCC_DIR}/lib)

SET(OOC_FOUND FALSE)
IF(OCC_LIB)
	SET(OCC_FOUND TRUE)
	MARK_AS_ADVANCED(OCC_LIB)
ENDIF(OCC_LIB)

IF(OCC_FOUND)
	MESSAGE(STATUS "Found opencascade: ${OCC_LIB}")
	SET(OCC_INC_DIR ${OCC_DIR}/inc CACHE FILEPATH "OpenCascade include directory.")
	MARK_AS_ADVANCED(OCC_PATH)
	MARK_AS_ADVANCED(OCC_INC_DIR)
ELSE(OCC_FOUND)
	MESSAGE(FATAL_ERROR "could not find opencascade")
ENDIF(OCC_FOUND)
