IF(NEKTAR_USE_SYSTEM_BLAS_LAPACK)
	SET(TEST_ENV $ENV{LAPACK_DIR})
	IF(NOT DEFINED LAPACK_DIR AND DEFINED TEST_ENV)
		SET(LAPACK_DIR $ENV{LAPACK_DIR})
	ENDIF()

	SET(TEST_ENV $ENV{BLAS_DIR})
	IF(NOT DEFINED BLAS_DIR AND DEFINED TEST_ENV)
		SET(BLAS_DIR $ENV{BLAS_DIR})
	ENDIF()

	SET(VENDOR Generic)
ELSEIF(NEKTAR_USE_OPENBLAS)
	SET(TEST_ENV $ENV{OPENBLAS_HOME})
	IF(NOT DEFINED BLAS_DIR AND DEFINED TEST_ENV)
		SET(BLAS_DIR $ENV{OPENBLAS_HOME})
	ENDIF()

	IF(NOT DEFINED LAPACK_DIR AND DEFINED TEST_ENV)
		SET(LAPACK_DIR $ENV{OPENBLAS_HOME})
	ENDIF()

	SET(VENDOR OpenBLAS)

ELSEIF(NEKTAR_USE_ACCELERATE_FRAMEWORK)

	SET(VENDOR Apple)

ELSEIF(NEKTAR_USE_ACML)

	SET(VENDOR ACML)
	
ENDIF()

SET(BLA_VENDOR ${VENDOR})

find_package(BLAS QUIET)
find_package(LAPACK QUIET)

IF(NEKTAR_USE_SYSTEM_BLAS_LAPACK)
	SET(BLAS_LAPACK ${BLAS_LIBRARIES} ${LAPACK_LIBRARIES})
ELSE()
	SET(BLAS_LAPACK ${LAPACK_LIBRARIES})
ENDIF()

IF (BLAS_LAPACK)
     MESSAGE(STATUS "Found Blas and Lapack")
ELSE()
  IF (NATIVE_BLAS_LAPACK_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find Native blas and lapack libraries.")
  ENDIF ()
ENDIF ()
