FIND_PATH(OCC_INCLUDE_DIR TopoDS.hxx PATHS /opt/local/include/oce)

FIND_LIBRARY(lPTKernel NAMES PTKernel PATHS /opt/local/lib)
FIND_LIBRARY(lTKernel NAMES TKernel PATHS /opt/local/lib)
FIND_LIBRARY(lTKMath NAMES TKMath PATHS /opt/local/lib)
FIND_LIBRARY(lTKBRep NAMES TKBRep PATHS /opt/local/lib)
FIND_LIBRARY(lTKIGES NAMES TKIGES PATHS /opt/local/lib)
FIND_LIBRARY(lTKSTEP NAMES TKSTEP PATHS /opt/local/lib)
FIND_LIBRARY(lTKSTEPAttr NAMES TKSTEPAttr PATHS /opt/local/lib)
FIND_LIBRARY(lTKSTEP209 NAMES TKSTEP209 PATHS /opt/local/lib)
FIND_LIBRARY(lTKSTEPBase NAMES TKSTEPBase PATHS /opt/local/lib)
FIND_LIBRARY(lTKShapeSchema NAMES TKShapeSchema PATHS /opt/local/lib)
FIND_LIBRARY(lTKGeomBase NAMES TKGeomBase PATHS /opt/local/lib)
FIND_LIBRARY(lTKGeomAlgo NAMES TKGeomAlgo PATHS /opt/local/lib)
FIND_LIBRARY(lTKG3d NAMES TKG3d PATHS /opt/local/lib)
FIND_LIBRARY(lTKG2d NAMES TKG2d PATHS /opt/local/lib)
FIND_LIBRARY(lTKXSBase NAMES TKXSBase PATHS /opt/local/lib)
FIND_LIBRARY(lTKPShape NAMES TKPShape PATHS /opt/local/lib)
FIND_LIBRARY(lTKTopAlgo NAMES TKTopAlgo PATHS /opt/local/lib)

SET(OCC_FOUND FALSE)
IF(lPTKernel AND OCC_INCLUDE_DIR)
    SET(OCC_FOUND TRUE)
    SET(OCC_LIBS ${lPTKernel} ${lTKernel} ${lTKMath} ${lTKBRep} ${lTKIGES} ${lTKSTEP} ${lTKSTEPAttr} ${lTKSTEP209} ${lTKSTEPBase} ${lTKShapeSchema} ${lTKGeomBase} ${lTKGeomAlgo} ${lTKG3d} ${lTKG2d} ${lTKXSBase} ${lTKPShape} ${lTKTopAlgo})
ENDIF(lPTKernel AND OCC_INCLUDE_DIR)

IF(OCC_FOUND)
        MESSAGE(STATUS "Found opencascade: ${OCC_LIBS}")
ELSE(OCC_FOUND)
        MESSAGE(FATAL_ERROR "could not find opencascade")
ENDIF(OCC_FOUND)