
SET(TEST_ENV $ENV{LAPACK_DIR})
IF(NOT DEFINED LAPACK_DIR AND DEFINED TEST_ENV)
	SET(LAPACK_DIR $ENV{LAPACK_DIR})
ENDIF()

SET(TEST_ENV $ENV{BLAS_DIR})
IF(NOT DEFINED BLAS_DIR AND DEFINED TEST_ENV)
	SET(BLAS_DIR $ENV{BLAS_DIR})
ENDIF()

SET(BLA_VENDOR Generic)

find_package(BLAS QUIET)
find_package(LAPACK QUIET)

IF (BLAS_FOUND AND LAPACK_FOUND)
  SET(NATIVE_BLAS_LAPACK_FOUND ON)
ENDIF ()

IF (NATIVE_BLAS_LAPACK_FOUND)
     MESSAGE(STATUS "Found Native Blas and Lapack")
ELSE(NATIVE_BLAS_LAPACK_FOUND)
  IF (NATIVE_BLAS_LAPACK_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find Native blas and lapack libraries.")
  ENDIF (NATIVE_BLAS_LAPACK_FIND_REQUIRED)
ENDIF (NATIVE_BLAS_LAPACK_FOUND)
