
SET(SCALAPACK_SEARCH_PATHS 
	${CMAKE_SOURCE_DIR}/ThirdParty/scalapack-2.0.2
	${CMAKE_SOURCE_DIR}/ThirdParty/scalapack-2.0.2/build/lib
	${CMAKE_SOURCE_DIR}/../ThirdParty/scalapack-2.0.2/
	${CMAKE_SOURCE_DIR}/../ThirdParty/scalapack-2.0.2/build/lib
    ${CMAKE_SOURCE_DIR}/ThirdParty/dist/lib 
    ${CMAKE_SOURCE_DIR}/../ThirdParty/dist/lib)

FIND_LIBRARY(SCALAPACK_LIB NAMES scalapack PATHS ${SCALAPACK_SEARCH_PATHS})


SET(SCALAPACK_FOUND FALSE)
IF (SCALAPACK_LIB)
  SET(SCALAPACK_FOUND TRUE)
  MARK_AS_ADVANCED(SCALAPACK_LIB)
ENDIF (SCALAPACK_LIB)

IF (SCALAPACK_FOUND)
  IF (NOT SCALAPACK_LIB_FIND_QUIETLY)
      MESSAGE(STATUS "Found ScaLAPACK")
  ENDIF (NOT SCALAPACK_LIB_FIND_QUIETLY)
ELSE(SCALAPACK_FOUND)
  IF (SCALAPACK_LIB_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find ScaLAPACK")
  ENDIF (SCALAPACK_LIB_FIND_REQUIRED)
ENDIF (SCALAPACK_FOUND)
