OPTION(NEKTAR_USE_PETSC
    "Enable PETSc parallel matrix solver support." OFF)

CMAKE_DEPENDENT_OPTION(THIRDPARTY_BUILD_PETSC
    "Build PETSc if needed" OFF
    "NEKTAR_USE_PETSC" OFF)

IF( NEKTAR_USE_PETSC )
    IF (THIRDPARTY_BUILD_PETSC)
        # TODO
    ELSE (THIRDPARTY_BUILD_PETSC)
        INCLUDE (FindPETSc)
        MESSAGE(STATUS "Found PETSc: ${PETSC_LIBRARIES}")
    ENDIF (THIRDPARTY_BUILD_PETSC)
ENDIF( NEKTAR_USE_PETSC )

INCLUDE_DIRECTORIES(${PETSC_INCLUDES})





