SET(NEKTAR_USE_VTK    OFF CACHE BOOL 
    "Use VTK library for utilities.")

IF( NEKTAR_USE_VTK )
    INCLUDE (FindVTK)
    IF (NOT VTK_FOUND)
        MESSAGE(FATAL_ERROR "VTK not found")
    ENDIF (NOT VTK_FOUND)
    INCLUDE (${VTK_USE_FILE})
    MARK_AS_ADVANCED(VTK_DIR)
    ADD_DEFINITIONS(-DNEKTAR_USING_VTK)
    INCLUDE_DIRECTORIES(${VTK_INCLUDE_DIRS})
ENDIF( NEKTAR_USE_VTK )

