OPTION(THIRDPARTY_BUILD_NIST_SPBLASTK
    "Build NIST Sparse BLAS" ON)

IF (THIRDPARTY_BUILD_NIST_SPBLASTK)
    INCLUDE(ExternalProject)
    EXTERNALPROJECT_ADD(
        spblastk0.9b
        PREFIX ${TPSRC}
        URL ${TPURL}/spblastk0.9b.tar.bz2
        URL_MD5 "93469940f03554939a4600f431eb4d99"
        DOWNLOAD_DIR ${TPSRC}
        CONFIGURE_COMMAND ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX:PATH=${TPSRC}/dist ${TPSRC}/src/spblastk0.9b
    )
    SET(NIST_SPARSE_BLAS sbtk CACHE FILEPATH
        "Path to NIST Sparse BLAS." FORCE)
    MARK_AS_ADVANCED(NIST_SPARSE_BLAS)
    LINK_DIRECTORIES(${TPSRC}/dist/lib)
    MESSAGE(STATUS "Build NIST Sparse BLAS: ${TPSRC}/dist/lib/lib${NIST_SPARSE_BLAS}.a")
ELSE (THIRDPARTY_BUILD_NIST_SPBLASTK)
    INCLUDE(FindNistSparseBlas)
ENDIF (THIRDPARTY_BUILD_NIST_SPBLASTK)

