#!/bin/bash

# Testing Spatial Accuracy with small dt 
#==========================================
# 1 elements mesh
echo "%L 2 error" > Mesh_1Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_1.xml

../../builds/ADRSolver/ADRSolver-g CFL_1.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_1Quads
done
#==========================================
# 4 elements mesh
echo "%L 2 error" > Mesh_4Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_4.xml

../../builds/ADRSolver/ADRSolver-g CFL_4.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_4Quads
done
#==========================================
# 9 elements mesh
echo "%L 2 error" > Mesh_9Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_9.xml

../../builds/ADRSolver/ADRSolver-g CFL_9.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_9Quads
done
#==========================================
# 16 elements mesh
echo "%L 2 error" > Mesh_16Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_16.xml

../../builds/ADRSolver/ADRSolver-g CFL_16.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_16Quads
done
#==========================================
# 25 elements mesh
echo "%L 2 error" > Mesh_25Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_25.xml

../../builds/ADRSolver/ADRSolver-g CFL_25.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_25Quads
done
#==========================================
# 36 elements mesh
echo "%L 2 error" > Mesh_36Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_36.xml

../../builds/ADRSolver/ADRSolver-g CFL_36.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_36Quads
done
#==========================================
# 49 elements mesh
echo "%L 2 error" > Mesh_49Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_49.xml

../../builds/ADRSolver/ADRSolver-g CFL_49.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_49Quads
done
#==========================================
# 64 elements mesh
echo "%L 2 error" > Mesh_64Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_64.xml

../../builds/ADRSolver/ADRSolver-g CFL_64.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_64Quads
done
#==========================================
# 81 elements mesh
echo "%L 2 error" > Mesh_81Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_81.xml

../../builds/ADRSolver/ADRSolver-g CFL_81.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_81Quads
done
#==========================================
# 100 elements mesh
echo "%L 2 error" > Mesh_100Quads
for P in 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
sed -i.tmp "s/NUMMODES.*/NUMMODES =\"$P\" TYPE=\"MODIFIED\" \/>/" CFL_100.xml

../../builds/ADRSolver/ADRSolver-g CFL_100.xml | grep "L 2" > tmp
err=`awk 'BEGIN{}; {ERR=$6}; END{print ERR}' tmp`
echo "$P     $err" >> Mesh_100Quads
done



