#!/bin/bash
SOLVER=./ADRSolver-g
test ! -x $SOLVER && echo "Solver $SOLVER not found." && exit

test -f results.txt && mv results.txt results.txt.bak

MAX_H=1
MAX_P=5
for opt in 0 2 3; do
    for h in $(seq 1 $MAX_H); do
        for P in $(seq 2 $MAX_P); do
            sed "s/#NUMMODES#/$P/" < CFL_$h.xml > tmp.xml
            if [ $opt -eq 0 ]; then
                sed -e "s/#OPTGLOBAL#/0/" \
                    -e "s/#OPTBLOCK#/0/g" \
                    -e "s/#OPTMAT#/0/g" < Opt.xml > tmp_opt.xml
            elif [ $opt -eq 2 ]; then
                sed -e "s/#OPTGLOBAL#/0/" \
                    -e "s/#OPTBLOCK#/0/g" \
                    -e "s/#OPTMAT#/1/g" < Opt.xml > tmp_opt.xml
            elif [ $opt -eq 3 ]; then
                sed -e "s/#OPTGLOBAL#/1/" \
                    -e "s/#OPTBLOCK#/0/g" \
                    -e "s/#OPTMAT#/0/g" < Opt.xml > tmp_opt.xml
            fi
            echo "Mesh: opt=$opt, h=$h, P=$P"
            $SOLVER tmp.xml > output.txt
            grep "L 2" output.txt | awk "{print $opt, $h, $P, \$6}" >> results.txt
        done
    done
done
rm -f tmp* output.txt
