#!/bin/bash
MAX_dt=5
for t in $(seq 2 $MAX_dt); do
    DT=$(echo "scale=9; 10^-$t" | bc)
    sed "s/#DT#/$DT/" < CFL_dt.xml > tmp.xml
    echo "Run: dt=$t"
    ./ADRSolver tmp.xml > output.txt
    grep "L 2" output.txt
    grep "L 2" output.txt | awk "{print $t, \$6}" >> results_dt.txt
done
rm -f tmp* output.txt
